[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://stresslo.com"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Set-Cookie"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; connect-src https://api.vixcera.bid ; script-src 'self' ; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200