[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://stresslo.com"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Set-Cookie"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(self 'https://api.vixcera.bid')"
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200